permissions:
  contents: read
name: checkdata

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  checkdata:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: プルリクエストの場合、PRブランチをチェックアウト
        if: github.event_name == 'pull_request'
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run checkdata.py
        run: python3 .github/workflows/checkdata.py
